export const bsis2b = [
  { name: "BARCOMA, Keren J", grade: 2.1, code: "K7X2L" },
  { name: "CABALLES, Cyrus John J.", grade: 5.0, code: "M9QVD" },
  { name: "CABANOS, Angelica S.", grade: 1.7, code: "Z4WPT" },
  { name: "CATAMIO, Janica Joy S.", grade: 2.9, code: "N8K3B" },
  { name: "HISTORILLO, Deserie M.", grade: 2.2, code: "FYR6J" },
  { name: "JANDUSAY, Angela D", grade: 1.8, code: "TX1ZM" },
  { name: "LEAL, Kyla Ann L", grade: 2.0, code: "B3LQX" },
  { name: "LICON, Rica An", grade: 2.0, code: "U5VND" },
  { name: "LOPE, Jheyron D.", grade: 2.4, code: "H2PWT" },
  { name: "MAGLACAS, Princess Diane M.", grade: 1.9, code: "J9CXL" },
  { name: "MALAPAD, Shiela Mae Q.", grade: 1.8, code: "V7NMB" },
  { name: "MALAPIT, Marijoy", grade: 2.2, code: "D4YKQ" },
  { name: "MAMENG, Jona L.", grade: 1.9, code: "R8TXL" },
  { name: "MIRAMBIL, Mary Grace A.", grade: 2.5, code: "Q1WZE" },
  { name: "MONLEON, Mark Julius G.", grade: 2.3, code: "L3JVD" },
  { name: "REANZARES, Anna Marie L.", grade: 2.1, code: "C7NXP" },
  { name: "RECTO, Juliven Keanne C.", grade: 2.4, code: "E9MTB" },
  { name: "SIENA, Lavern L.", grade: 2.2, code: "W6YKL" },
  { name: "SIGUE, Oharah P.", grade: 2.1, code: "X5LQZ" },
  { name: "WAQUIZ, Fredeline L.", grade: 2.1, code: "Z0RWD" },
];
