export const bsis2c = [
  { name: "ALABAT, Honeylen M.", grade: 2.2, code: "Z8X2L" },
  { name: "CONVOCAR, Lealyn L.", grade: 2.3, code: "MOR9Q" },
  { name: "DELA ROSA, Enric James L.", grade: 2.2, code: "VPL7D" },
  { name: "DELOS SANTOS, Elgie P.", grade: 1.9, code: "XEN5B" },
  { name: "GUTIERREZ, John Carloe S.", grade: 2.7, code: "K3TWM" },
  { name: "HISTORILLO, Checo L", grade: 2.6, code: "RQJ8Z" },
  { name: "JASMIN, Joshua Morales", grade: 2.7, code: "Y5NFX" },
  { name: "LACERNA, Christlyn M.", grade: 1.6, code: "D7WKL" },
  { name: "LASTICA, Erich  Wyane P.", grade: 2.4, code: "LU39E" },
  { name: "LAYLAY, Jake F.", grade: 2.0, code: "BHT4M" },
  { name: "LOSLOS, Janmhar P.", grade: 2.1, code: "Q2YXR" },
  { name: "LOSLOS, Ma.angela A.", grade: 2.8, code: "JKN5V" },
  { name: "MAGALANG, Thristan Joseph M.", grade: 2.8, code: "FLO8T" },
  { name: "MAJABA, Jaycel S", grade: 2.2, code: "GZ13W" },
  { name: "MALCO, Jhon Gerald V", grade: 2.7, code: "XE9UM" },
  { name: "MALING, John Lorence M.", grade: 2.3, code: "TQV7N" },
  { name: "MARTINEZ, Cristel Shin M.", grade: 2.3, code: "WKD2P" },
  { name: "MATAYA, Ashley Ann", grade: 2.2, code: "SML6J" },
  { name: "NAMBIO, Billy Joe S.", grade: 2.5, code: "H3OVC" },
  { name: "ORNEDO, Lyka Sarah M.", grade: 2.8, code: "PYZ5L" },
  { name: "OSMILLO, Mervin Jr. B", grade: 2.2, code: "NRX8D" },
  { name: "PACAO, Jimwell S", grade: 2.2, code: "KUB4T" },
  { name: "QUIJANO, Jhon Rafael M.", grade: 2.6, code: "DPL9E" },
  { name: "REANZARES, Chayrene May S.", grade: 2.1, code: "ZYW7F" },
  { name: "REGALADO, Kayla Maris M.", grade: 2.0, code: "CTO3V" },
  { name: "ROCERO, Chrisha Mae L.", grade: 2.5, code: "BRK6M" },
  { name: "ROQUEZA, Jake Allen S.", grade: 2.3, code: "QEP1N" },
  { name: "SAPUNGAN, Christian R.", grade: 2.3, code: "MJX5L" },
  { name: "SERDEÑA, Alfrancis Paul L.", grade: 2.6, code: "UYT9Z" },
  { name: "SEVILLA, Anthon F.", grade: 1.9, code: "XLC4Q" },
];
