export const bsit1e = [
  { name: "ABADECIO, Gerald", grade: 2.1, code: "Z8X2L" },
  { name: "ALAVANZAS, Richard Benedict J.", grade: 2.6, code: "MOR9Q" },
  { name: "ALINGOD, Lois Raien M.", grade: 4.3, code: "VPL7D" },
  { name: "BALANE, Carlo R.", grade: 1.9, code: "XEN5B" },
  { name: "BALLERDA, Micheal Vincent M.", grade: 2.5, code: "K3TWM" },
  { name: "CAPITIN, Jaq Maica M.", grade: 2.7, code: "RQJ8Z" },
  { name: "CONCHA, John Philip L.", grade: "INC", code: "Y5NFX" },
  { name: "DISTAJO, John Benedict R.", grade: 2.6, code: "D7WKL" },
  { name: "FIRMEZA, Carl Ian G.", grade: 2.6, code: "LU39E" },
  { name: "FRIAS, Danica R.", grade: 1.7, code: "BHT4M" },
  { name: "LABAO, Jimmel M.", grade: "INC", code: "Q2YXR" },
  { name: "LATORENA, Victoria Nicolette P.", grade: 2.3, code: "JKN5V" },
  { name: "LAYLAY, Merianne M.", grade: 2.0, code: "FLO8T" },
  { name: "LIMBO, Britney C.", grade: 2.3, code: "GZ13W" },
  { name: "LIMPIADA, Dharen S.", grade: 1.9, code: "XE9UM" },
  { name: "LUMAGUI, Hany Leth A.", grade: 1.8, code: "TQV7N" },
  { name: "MACARANG, Emhar M.", grade: 4.1, code: "WKD2P" },
  { name: "MADRIGAL, Kimberly M.", grade: 2.3, code: "SML6J" },
  { name: "MAGPARANGALAN, J-Ber S.", grade: 2.1, code: "H3OVC" },
  { name: "MALACAS, Bea S.", grade: 2.7, code: "PYZ5L" },
  { name: "MALAPAD, Jay patrick E.", grade: 2.9, code: "NRX8D" },
  { name: "MAMING, Lance Vrayan S.", grade: 1.7, code: "KUB4T" },
  { name: "MANOOS, Karish Montemar", grade: 2.8, code: "DPL9E" },
  { name: "NABING, Llewelyn Chate C.", grade: 2.9, code: "ZYW7F" },
  { name: "NALING, Jean Jewell Kris O.", grade: 2.0, code: "CTO3V" },
  { name: "NOGALES, John Harris Jim", grade: 4.7, code: "BRK6M" },
  { name: "PARAGAS, Ken Zander M.", grade: 1.6, code: "QEP1N" },
  { name: "QUINTO, Princess Erlain M.", grade: 2.3, code: "MJX5L" },
  { name: "RAYOS, Lyra Jane P.", grade: 2.4, code: "UYT9Z" },
  { name: "REVILLA, Lhorenz Andrei M.", grade: 1.9, code: "XLC4Q" },
  { name: "RICAMARA, Robert Tristan O.", grade: 2.6, code: "MMLLWQ" },
  { name: "ROSAS, Maria Mercy Joy V.", grade: 2.4, code: "MASKZZ" },
  { name: "SALCEDO, Lerald S.", grade: 2.1, code: "GGGPLK" },
  { name: "VALES, Jhymlie L.", grade: 1.9, code: "POPOASK" },
];
